version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springbootdb
      MYSQL_USER: springbootuser
      MYSQL_PASSWORD: springbootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springbootdb
      SPRING_DATASOURCE_USERNAME: springbootuser
      SPRING_DATASOURCE_PASSWORD: springbootpassword
    networks:
      - springboot-network

  springboot-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springbootdb
      SPRING_DATASOURCE_USERNAME: springbootuser
      SPRING_DATASOURCE_PASSWORD: springbootpassword
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  mysql_data: